// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts"
// @generated from file test.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file test.proto.
 */
export declare const file_test: GenFile;

/**
 * @generated from message exampleMessage
 */
export declare type exampleMessage = Message<"exampleMessage"> & {
  /**
   * @generated from field: float exampleFloat = 1;
   */
  exampleFloat: number;
};

/**
 * Describes the message exampleMessage.
 * Use `create(exampleMessageSchema)` to create a new message.
 */
export declare const exampleMessageSchema: GenMessage<exampleMessage>;

