// @generated by protoc-gen-es v2.12.0 with parameter "target=js+dts"
// @generated from file test.proto (syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file test.proto.
 */
export const file_test = /*@__PURE__*/
  fileDesc("Cgp0ZXN0LnByb3RvIiYKDmV4YW1wbGVNZXNzYWdlEhQKDGV4YW1wbGVGbG9hdBgBIAEoAkIfQglUZXN0UHJvdG9QAVoQdGVzdC5jb20vZXhhbXBsZWIGcHJvdG8z");

/**
 * Describes the message exampleMessage.
 * Use `create(exampleMessageSchema)` to create a new message.
 */
export const exampleMessageSchema = /*@__PURE__*/
  messageDesc(file_test, 0);

