// Below section copied from code generated by buf.build/bufbuild/es
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
export const file_test = /*@__PURE__*/
    fileDesc("Cgp0ZXN0LnByb3RvIiYKDmV4YW1wbGVNZXNzYWdlEhQKDGV4YW1wbGVGbG9hdBgBIAEoAkIfQglUZXN0UHJvdG9QAVoQdGVzdC5jb20vZXhhbXBsZWIGcHJvdG8z");
export const exampleMessageSchema = /*@__PURE__*/
    messageDesc(file_test, 0);

// Basic test
import { fromJson} from "@bufbuild/protobuf";

const pbIn = {"exampleFloat":  3.4028235e+38}
console.log(
    fromJson(exampleMessageSchema, pbIn)
);